# Generated by Django 5.0 on 2023-12-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_recentwork_service_delete_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icom',
        ),
    ]
